// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.Airbender2017;

import org.usfirst.frc692.Airbender2017.commands.AutonomousCommand;
import org.usfirst.frc692.Airbender2017.commands.AutonomousForward;
import org.usfirst.frc692.Airbender2017.commands.ClimbUp;
import org.usfirst.frc692.Airbender2017.commands.DriveWithOneJoystick;
import org.usfirst.frc692.Airbender2017.commands.DumpTruckMoter;
import org.usfirst.frc692.Airbender2017.commands.DumpTruckReset;
import org.usfirst.frc692.Airbender2017.commands.GearClose;
import org.usfirst.frc692.Airbender2017.commands.GearOpen;
import org.usfirst.frc692.Airbender2017.commands.SwitchCameras;
import org.usfirst.frc692.Airbender2017.commands.UnloadDumpTruck;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton switchCamerasButton;
    public Joystick joystickOneStickDrive;
    public JoystickButton climbUpButton;
    public JoystickButton gearOpenButton;
    public JoystickButton gearCloseButton;
    public Joystick gamepad;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        gamepad = new Joystick(1);
        
        gearCloseButton = new JoystickButton(gamepad, 6);
        gearCloseButton.whenPressed(new GearClose());
        gearOpenButton = new JoystickButton(gamepad, 5);
        gearOpenButton.whenPressed(new GearOpen());
        climbUpButton = new JoystickButton(gamepad, 2);
        climbUpButton.whileHeld(new ClimbUp());
        joystickOneStickDrive = new Joystick(0);
        
        switchCamerasButton = new JoystickButton(joystickOneStickDrive, 1);
        switchCamerasButton.whenPressed(new SwitchCameras());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("GearOpen", new GearOpen());
        SmartDashboard.putData("GearClose", new GearClose());
        SmartDashboard.putData("ClimbUp", new ClimbUp());
        SmartDashboard.putData("DriveWithOneJoystick", new DriveWithOneJoystick());
        SmartDashboard.putData("SwitchCameras", new SwitchCameras());
        SmartDashboard.putData("AutonomousForward", new AutonomousForward());
        SmartDashboard.putData("DumpTruckReset ", new DumpTruckReset());
        SmartDashboard.putData("UnloadDumpTruck", new UnloadDumpTruck());
        SmartDashboard.putData("DumpTruckMoter", new DumpTruckMoter());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystickOneStickDrive() {
        return joystickOneStickDrive;
    }

    public Joystick getGamepad() {
        return gamepad;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

