// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.Airbender2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.VictorSP;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainRightBackSpeedController;
    public static SpeedController driveTrainLeftFrontSpeedController;
    public static SpeedController driveTrainLeftBackSpeedController;
    public static SpeedController driveTrainRightFrontSpeedController;
    public static RobotDrive driveTrainRobotDrive41;
    public static SpeedController climberClimberSpeedController;
    public static DoubleSolenoid gearPistonGearPistonSolenoid;
    public static Compressor pneumaticsCompressor;
    public static DoubleSolenoid dumpTruckDumpTruckSolenoidOne;
    public static DoubleSolenoid dumpTruckDumpTruckSolenoidTwo;
    public static SpeedController dumpTruckDumpTruckSpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightBackSpeedController = new VictorSP(0);
        LiveWindow.addActuator("DriveTrain", "RightBackSpeedController", (VictorSP) driveTrainRightBackSpeedController);
        
        driveTrainLeftFrontSpeedController = new VictorSP(1);
        LiveWindow.addActuator("DriveTrain", "LeftFrontSpeedController", (VictorSP) driveTrainLeftFrontSpeedController);
        
        driveTrainLeftBackSpeedController = new VictorSP(2);
        LiveWindow.addActuator("DriveTrain", "LeftBackSpeedController", (VictorSP) driveTrainLeftBackSpeedController);
        
        driveTrainRightFrontSpeedController = new VictorSP(3);
        LiveWindow.addActuator("DriveTrain", "RightFrontSpeedController", (VictorSP) driveTrainRightFrontSpeedController);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainLeftFrontSpeedController, driveTrainLeftBackSpeedController,
              driveTrainRightFrontSpeedController, driveTrainRightBackSpeedController);
        
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);

        climberClimberSpeedController = new VictorSP(4);
        LiveWindow.addActuator("Climber", "ClimberSpeedController", (VictorSP) climberClimberSpeedController);
        
        gearPistonGearPistonSolenoid = new DoubleSolenoid(0, 4, 5);
        LiveWindow.addActuator("GearPiston", "GearPistonSolenoid", gearPistonGearPistonSolenoid);
        
        pneumaticsCompressor = new Compressor(0);
        
        
        dumpTruckDumpTruckSolenoidOne = new DoubleSolenoid(0, 1, 2);
        LiveWindow.addActuator("DumpTruck", "DumpTruckSolenoidOne", dumpTruckDumpTruckSolenoidOne);
        
        dumpTruckDumpTruckSolenoidTwo = new DoubleSolenoid(0, 0, 3);
        LiveWindow.addActuator("DumpTruck", "DumpTruckSolenoidTwo", dumpTruckDumpTruckSolenoidTwo);
        
        dumpTruckDumpTruckSpeedController = new Talon(5);
        LiveWindow.addActuator("DumpTruck", "DumpTruckSpeedController", (Talon) dumpTruckDumpTruckSpeedController);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
