// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.Airbender2017.subsystems;

import org.usfirst.frc692.Airbender2017.RobotMap;
import org.usfirst.frc692.Airbender2017.commands.*;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController rightBackSpeedController = RobotMap.driveTrainRightBackSpeedController;
    private final SpeedController leftFrontSpeedController = RobotMap.driveTrainLeftFrontSpeedController;
    private final SpeedController leftBackSpeedController = RobotMap.driveTrainLeftBackSpeedController;
    private final SpeedController rightFrontSpeedController = RobotMap.driveTrainRightFrontSpeedController;
    private final RobotDrive robotDrive41 = RobotMap.driveTrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveWithOneJoystick());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void moveForwardAuton()
    {
    	robotDrive41.drive(1, 0);
    }
    // DriveTrain moves forward at 100% power for the AutonomousCommand.
    // TTT 2-4-17
    
    public void robotStopAuton()
    {
    	robotDrive41.drive(0, 0);
    }
    // DriveTrain doesn't move when joysticks aren't touched for AutonomousCommand.
    // TTT 2-4-17
}

