// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.Airbender2017.subsystems;

import org.usfirst.frc692.Airbender2017.RobotMap;
import org.usfirst.frc692.Airbender2017.commands.*;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DumpTruck extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid dumpTruckSolenoidOne = RobotMap.dumpTruckDumpTruckSolenoidOne;
    private final DoubleSolenoid dumpTruckSolenoidTwo = RobotMap.dumpTruckDumpTruckSolenoidTwo;
    private final SpeedController dumpTruckSpeedController = RobotMap.dumpTruckDumpTruckSpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void resetDumpTruck() 
    {
    	dumpTruckSolenoidOne.set(Value.kReverse);
    	dumpTruckSolenoidTwo.set(Value.kReverse);
    }
    // cause solenoid to close therefore the dumpTruck lower to reset itself. 
    // AVC 2/ 4/ 17
    
    public void solenoidOff()
    {
    	dumpTruckSolenoidOne.set(Value.kOff);
    	dumpTruckSolenoidTwo.set(Value.kOff);
    }
    // air is turned off on gear mechanism 
    // AVC 2/ 4/ 17
    
    public void dump()
    {
    	dumpTruckSolenoidOne.set(Value.kForward);
    	dumpTruckSolenoidTwo.set(Value.kForward);
    }
    // Cause solenoid to open therefore the dumpTruck raises to dump its contents.
    // AVC 2/4/17
    
    public void dumpTruckSpedController()
    {
    	dumpTruckSpeedController.set(0.7);
    	
    }
    // moving 70% power (for Katie K) 
    // AVC 2/4/17
    
    public void dumpTruckBackwards() 
    {
    	dumpTruckSpeedController.set(-0.7);
    }
    // does the opposite goes backward 70% power back   
    // AVC 2/4/17 
}

